apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: zb9jb6k6q-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:dc3094288242544f4191d980555fef5bfe9f80cd@sha256:2f8a31bc958a34acd6ab930d56774c9e8e12d08736f74f6e7973ae287e2858fa
          name: container-image
